# Dependencies
markdown: kramdown
highlighter: rouge


# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Rainvoo
tagline:             '请看石上藤萝月，已映洲前芦笛花'
description:         '这是一个个人博客，主要写一些读书心得和对世界的观察，作者是  <a href="https://github.com/rainvoo" target="_blank">@润悟</a>.'
url:                 'http://rainvoo.com'
baseurl:
paginate:            4

# About/contact
author:
  name:              '润悟'
  url:               https://github.com/rainvoo
  email:             hrwsmart@gmail.com

# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# 指定摘要识别符号
excerpt_separator:  '<!--more-->'
